--- #YAML:1.0
name:               Cisco-Management
version:            0.04
abstract:           Interface for Cisco Management
author:
    - Michael Vincent <vin at vinsworld dot com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Socket:     ~
    Net::SNMP:      ~
    Sys::Hostname:  ~
    Test::Simple:   ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
